=== FreeBSD Foundation

Links: +
link:https://freebsdfoundation.org/[FreeBSD Foundation] URL: link:https://freebsdfoundation.org/[] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[] +
link:https://freebsdfoundation.org/donate/[Donate] URL: link:https://freebsdfoundation.org/donate/[] +
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[] +
link:https://freebsdfoundation.org/journal/[FreeBSD Journal] URL: link:https://freebsdfoundation.org/journal/[] +
link:https://freebsdfoundation.org/our-work/events/[Foundation Events] URL: link:https://freebsdfoundation.org/our-work/events/[]

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to supporting and promoting the FreeBSD Project and worldwide community, and helping to advance the state of FreeBSD.
We do this in both technical and non-technical ways.
We are 100% supported by donations from individuals and corporations and those investments help us fund the:

* Software development projects to implement features and functionality in FreeBSD
* Sponsor and organize conferences and developer summits to provide collaborative opportunities and promote FreeBSD
* Purchase and support of hardware to improve and maintain FreeBSD infrastructure
* Resources to improve security, quality assurance, and continuous integration efforts
* Materials and staff needed to promote, educate, and advocate for FreeBSD
* Collaboration between commercial vendors and FreeBSD developers
* Representation of the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity

==== Operations

==== OS Improvements
During the second quarter of 2024, 204 src, 50 ports, and 11 doc tree commits identified The FreeBSD Foundation as a sponsor.

The Foundation is currently sponsoring eight active projects.

* mailto:christos@FreeBSD.org[Christos Margiolis] continues work to improve FreeBSD's audio stack and provide audio developers with useful tools and frameworks to make sound development on FreeBSD easier.
Read more in mailto:christos@FreeBSD.org[Christos Margiolis] <<_audio_stack_improvements,Audio Stack Improvements>> report entry.

* mailto:pjd@FreeBSD.org[Pawel Dawidek] is in the final stages of a project to add hierarchical rate limits to OpenZFS.
The configured limits for bandwidth and operations will work like quotas.
If a child dataset is configured with a higher limit than its parent, the parent's lower limit will be enforced.
For details, refer to Pawel's link:https://github.com/openzfs/zfs/pull/16205[pull request in the OpenZFS repository].

* Long-term contractor mailto:olce@FreeBSD.org[Olivier Certner] was active in a few different parts of the tree:
** man:rtprio[2]: Updated the number of queues per runqueue from 64 to 256
** UnionFS: reviewed work from mailto:jah@FreeBSD.org[Jason A. Harmening]
   Jason's work fixes many locking problems (wild accesses without locks, deadlocks, etc.), in particular in unionfs_rename() and improves locking logic.
** Vnode recycling/ZFS ARC reclaim: Reviewed a fix for link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275594[bug #275594], liaised with upstream to obtain and test a backport, had an EN issued and applied as 13.3-RELEASE-p2, and started longer term work to improve the vnode reclaiming mechanisms and have ZFS pass the right information
** ULE scheduler: Updated to work on a single runqueue instead of 3 for POSIX compliance with respect to the number of distinct SCHED_FIFO/SCHED_RR priority levels
** Miscellaneous: Many (26) reviews, ports updates, and investigated DRM problems
** Published a link:https://freebsdfoundation.org/eurobsdcon-2023/[EuroBSDCon 2023 conference report in the FreeBSD Journal].

** mailto:pierre@freebsdfoundation.org[Pierre Pronchery] continue work on a security-focused with the Foundation.
His duties included:
* working on a conversion tool from link:https://vuxml.freebsd.org/freebsd/index.html[VuXML] to link:https://ossf.github.io/osv-schema/[OSV]
* automating the generation of VuXML reports across all ports with link:https://www.freshports.org/security/osv-scanner/[security/osv-scanner]
* running Coverity Scan reports around bhyve and assisting to rectify the reported defects

* mailto:mhorne@FreeBSD.org[Mitchell Horne] presented his RISC-V work at the FreeBSD developer summit.
You can read about his work this quarter in the <<_???>> report entry.

* Work continued on the joint project began between Advanced Micro Devices (AMD) and The FreeBSD Foundation to develop a complete FreeBSD AMD IOMMU driver.
  This work will allow FreeBSD to fully support greater than 256 cores with features such as CPU mapping and will also include bhyve integration.
  mailto:kib@FreeBSD.org[Konstantin Belousov] has been working on various parts of the project, including driver attachment, register definitions, an ACPI table parser, and utility functions.
  Two key components that need to be completed are context handling, which is mostly a generalization of Intel DMAR code, and page table creation.
  After this, the AMD driver's enable bit can be turned on for testing.
  To follow all of Konstantin's work, look for src commits tagged with Sponsored by fields for Advanced Micro Devices (AMD) and The FreeBSD Foundation.

* The Vector Packet Processor (VPP) is an open-source, high-performance user space networking stack that provides fast packet processing suitable for software-defined networking and network function virtualization applications.
  mailto:thj@FreeBSD.org[Tom Jones] wrapped up his part on a project to port VPP to FreeBSD.
  The code has been shared with RG Nets, a co-sponsor of the work, for extensive testing.
  
* mailto:bz@FreeBSD.org[Björn Zeeb] continued to improve wireless networking on FreeBSD.
  As with last quarter, focus was mainly on fixing bug fixes and improving stability.
  Most of Björn's 30+ src commits were to LinuxKPI and net80211 code.

FreeBSD's 11 Google Summer of Code projects are well under way.

(There may be some GSoC entries, so link to them when they are submitted.  The projects wiki can be found from the 2024 link on https://www.freebsd.org/projects/summerofcode/.)

==== Continuous Integration and Workflow Improvement
As part of our continued support of the FreeBSD Project, the Foundation supports a full-time staff member dedicated to improving the Project's continuous integration system and the test infrastructure.
The full update can be found within the quarterly status report.

==== Partnerships and Research

==== Advocacy
The first quarter of 2024 marked the beginning of a link:https://freebsdfoundation.org/blog/march-2024-advocacy-update/[new era] for the Foundation Advocacy team.

==== Fundraising

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to protect them.
We also provide legal support for the core team to investigate questions that arise.

Go to link:https://freebsdfoundation.org[] to find more about how we support FreeBSD and how we can help you!
